### ISSUE TITLE
Verification du pattern Adapter

### ISSUE THREAD

**Issue by Christiantaguejou** [PolytechLyon/isi3-tp1-graph-looser-lombardo-taguejou#1]
J'aimerai d'abord vérifier qu'on bien compris le pattern Adapter:
- On veut créer un Graph non orienté à partir de l'interface IUndirectedGraphe
- Pour ça on va implémenter la classe UndirectedGraphe qui va "adapter" l'interface de IUndirectedGraphe de manière à ce qu'à la sortie de cette classe on ait un objet Graph.

Si on a bien compris le pattern, est ce que vous pourriez regarder comment on a implémenté la classe UndirectedGraphe ? 
On bloque sur la méthode addEdge(); on ne sait pas comment l'implémenté à partir de la classe Graphe.  Est ce que qu'il vaut mieux créer une classe Arête ou se servir de la classe Arc qui existe déjà ?
 
Merci d'avance

**Comment by Slashgear** [comment]
Non non le pattern Adapter sert à `adapter` des fonctionnalités déjà présentent dans une implémentation de contrat par composition.

Ici on adapte les implémentations des fonctions de l'interface IGraph de Graph dans UndirectedGraph en ajoutant un attribut de type IGraph/Graph

**Comment by Slashgear** [comment]
Est ce que cela répond à ta question ? Si oui Close ton Issue. ça me permet de suivre ce qu'il me reste à faire.
