### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-tp1-graph-looser-lombardo-taguejou#2]
- [x] Les deux algo de parcours sont quasi les mêmes. Il y a du code en commun 
DRY

- 👍 le rapport est bien

- [x] la méthode hascode servirait à quoi si elle était implémentée dans Node ?

- [x] Ici le type pourrait être IGraph, pourquoi ?
https://github.com/PolytechLyon/isi3-tp1-graph-looser-lombardo-taguejou/blob/cf9033381edd8790f54cda9ebd55413346fe04c6/src/main/java/graph/UndirectedGraph.java#L7

**Comment by Christiantaguejou** [comment]
2) Cette méthode pourrait permettre de savoir si un noeud a été marqué lors d'un parcours.
3) Si on avait utilisé IGraph, il nous aurait fallu implémenté totalement les méthodes addEdge et hasEdge. Or les méthodes addArc et hasArc sont présentent dans l'interface IDirectedGraph et donc implémenté dans la classe Graph. Ainsi, en instanciant un objet Graph, on peut se servir des méthodes addArc et hasArc.

**Comment by Christiantaguejou** [comment]
HashCode permettra de créer un identifiant unique pour chaque Node ce qui facilitera l'utilisation de la méthode equals. Quand la méthode equals sera appelé, on comparera les hashcode, s'ils sont pareils, alors les deux objets sont égaux.

**Comment by Slashgear** [comment]
elle sert à d'autres choses encore ? Parlons de manière plus général en java, à quoi sert la méthode `hashcode`

**Comment by Christiantaguejou** [comment]
La méthode hashcode retourne un identifiant unique d'un objet. Deux objets ayant des paramètres différentes peuvent avoir le même valeur de hash, mais deux objets ayant des paramètres égaux doivent retourner la même valeur de hash.

**Comment by Slashgear** [comment]
Ok mais par exemple quel pourrait être l'intérêt sur les HashMap en Java ?
Rappel, une HashMap ne peut pas avoir deux clés identiques ?

**Comment by Christiantaguejou** [comment]
Quand on insère un élément dans une HashMap, le hashCode de l'élément est calculé et est utilisé pour savoir où stocké l'élément dans le HashMap. Lorsqu'on cherchera un objet dans la liste à partir de sa clé, le hashCode de cette clé nous permettra de savoir où chercher l'objet.

**Comment by Slashgear** [comment]
👌
